name = "api_littleeleven"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = [ "nodejs_compat" ]

# env
vars = { ENVIRONMENT = "production", BUCKET_NAME = "littleeleven" }
route = { pattern = "api.littleeleven.com", custom_domain = true }
d1_databases = [ { binding = "DB", database_name = "littleeleven", database_id = "c6ca0e33-ea58-48d3-b779-a21f9a063812" }, ]
r2_buckets = [ { binding = "BUCKET", bucket_name = "littleeleven" } ]

[triggers]
crons = []

[observability]
enabled = true
